import argparse
import sys
from pathlib import Path
from minecraft_server_wizard.mcapi import download_server_jar, resolve_version

JVM_FLAGS = [
    "-XX:+UseG1GC",
    "-XX:+ParallelRefProcEnabled",
    "-XX:MaxGCPauseMillis=200",
    "-XX:+UnlockExperimentalVMOptions",
    "-XX:+DisableExplicitGC",
    "-XX:+AlwaysPreTouch",
    "-XX:G1NewSizePercent=30",
    "-XX:G1MaxNewSizePercent=40",
    "-XX:G1HeapRegionSize=8m",
    "-XX:G1ReservePercent=20",
    "-XX:G1HeapWastePercent=5",
    "-XX:G1MixedGCCountTarget=4",
    "-XX:InitiatingHeapFraction=15",
    "-XX:G1MixedGCLiveThresholdPercent=90",
    "-XX:G1RSetUpdatingPauseTimePercent=5",
    "-XX:SurvivorRatio=32",
    "-XX:+PerfDisableSharedMem",
    "-XX:MaxTenuringThreshold=1"
]

def update_properties_file(filepath: Path, overrides: dict):
    """
    Updates an existing server.properties file, overriding or adding specified keys
    while preserving comments and line order where possible.
    """
    if not filepath.exists():
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("# Generated by minecraft-server-wizard\n")
            for k, v in overrides.items():
                f.write(f"{k}={v}\n")
        return

    lines = []
    seen_keys = set()
    
    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    new_lines = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            new_lines.append(line)
            continue
        
        if "=" in stripped:
            k, v = stripped.split("=", 1)
            k = k.strip()
            # FIXME: This will break if a key is commented out but we wanted to override it. Needs full parser logic later.
            if k in overrides:
                new_lines.append(f"{k}={overrides[k]}\n")
                seen_keys.add(k)
            else:
                new_lines.append(line)
                seen_keys.add(k)
        else:
            new_lines.append(line)

    for k, v in overrides.items():
        if k not in seen_keys:
            # print(f"Adding new property: {k}={v}")
            new_lines.append(f"{k}={v}\n")

    with open(filepath, "w", encoding="utf-8") as f:
        f.writelines(new_lines)

def setup_server(server_dir: Path, server_type: str, version: str, ram_gb: int, overrides: dict):
    server_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"Resolving version '{version}' for {server_type}...")
    try:
        resolved = resolve_version(server_type, version)
    except Exception as e:
        print(f"Error resolving version: {e}", file=sys.stderr)
        sys.exit(1)

    jar_name = f"{server_type}-{resolved}.jar"
    jar_path = server_dir / jar_name

    if not jar_path.exists():
        print(f"Downloading {jar_name}...")
        try:
            download_server_jar(server_type, resolved, jar_path)
        except Exception as e:
            print(f"Failed to download server JAR: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print(f"Found existing {jar_name}, skipping download.")

    eula_path = server_dir / "eula.txt"
    if not eula_path.exists():
        with open(eula_path, "w", encoding="utf-8") as f:
            f.write("eula=true\n")
            
    prop_path = server_dir / "server.properties"
    
    props_to_apply = {
        "motd": "A Minecraft Server managed by Wizard",
        "server-port": "25565",
        "online-mode": "true",
        "max-players": "20"
    }
    props_to_apply.update(overrides)
    
    update_properties_file(prop_path, props_to_apply)

    bat_path = server_dir / "run.bat"
    xms = f"-Xms{ram_gb}G"
    xmx = f"-Xmx{ram_gb}G"
    
    flags_str = " ".join(JVM_FLAGS)
    
    bat_content = (
        "@echo off\n"
        f"java {xms} {xmx} {flags_str} -jar {jar_name} nogui\n"
        "pause\n"
    )
    
    with open(bat_path, "w", encoding="utf-8") as f:
        f.write(bat_content)
        
    print(f"Server configured successfully in {server_dir}!")
    print("To start the server, run the generated run.bat file.")

def main():
    parser = argparse.ArgumentParser(
        description="Bootstrap and configure Minecraft servers on Windows."
    )
    parser.add_argument("--dir", "-d", default=".", help="Directory to setup the server in")
    parser.add_argument("--type", "-t", choices=["vanilla", "paper"], default="paper", help="Server type")
    parser.add_argument("--ver", "-v", default="latest", help="Minecraft version (e.g. 1.20.2, latest)")
    parser.add_argument("--ram", "-r", type=int, default=4, help="RAM in GB allocated to the server")
    parser.add_argument(
        "--prop", "-p",
        action="append",
        default=[],
        help="Property overrides in key=val format (can be used multiple times)"
    )
    
    args = parser.parse_args()
    
    overrides = {}
    for p in args.prop:
        if "=" not in p:
            print(f"Error: Invalid property format '{p}'. Must be key=value", file=sys.stderr)
            sys.exit(1)
        k, v = p.split("=", 1)
        overrides[k.strip()] = v.strip()
        
    server_dir = Path(args.dir)
    setup_server(server_dir, args.type, args.ver, args.ram, overrides)

if __name__ == "__main__":
    main()
